package com.opinion.model;

// Generated 2014-3-31 18:49:57 by Hibernate Tools 4.0.0

/**
 * Weibo generated by hbm2java
 */
public class Weibo implements java.io.Serializable {

	private Integer id;
	private String content;

	public Weibo() {
	}

	public Weibo(String content) {
		this.content = content;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
