/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'north',
                    split: true,
                    height: 50,
                    title: '基于GIS的农地流转网络舆情区域风险分析'
                },
                {
                    xtype: 'panel',
                    region: 'west',
                    split: true,
                    width: 150,
                    layout: {
                        type: 'accordion'
                    },
                    collapsible: true,
                    title: '管理面板',
                    items: [
                        {
                            xtype: 'treepanel',
                            title: '舆情信息获取',
                            root: {
                                expanded: true,
                                children: [
                                    {
                                        id: 'DataCratchTab',
                                        text: '新浪微博数据获取',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: '',
                                        text: 'QQ微博数据获取',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: '',
                                        text: '信息来源设置',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: '',
                                        text: '信息获取属性设置',
                                        icon: '',
                                        leaf: true
                                    }
                                ]
                            },
                            rootVisible: false,
                            viewConfig: {

                            },
                            listeners: {
                                selectionchange: {
                                    fn: me.onTreepanelSelectionChange,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'treepanel',
                            title: '舆情信息分类',
                            root: {
                                expanded: true,
                                children: [
                                    {
                                        id: '',
                                        text: '地名语料库设置',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: '',
                                        text: '舆情主题设置',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: '',
                                        text: '舆情主题关键词库',
                                        icon: '',
                                        leaf: true
                                    }
                                ]
                            },
                            rootVisible: false,
                            viewConfig: {

                            },
                            listeners: {
                                selectionchange: {
                                    fn: me.onTreepanelSelectionChange1,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'treepanel',
                            title: '区域风险分析',
                            root: {
                                expanded: true,
                                children: [
                                    {
                                        id: '',
                                        text: '统计报表设置',
                                        icon: '',
                                        leaf: true
                                    }
                                ]
                            },
                            rootVisible: false,
                            viewConfig: {

                            },
                            listeners: {
                                selectionchange: {
                                    fn: me.onTreepanelSelectionChange2,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'treepanel',
                            title: '区域风险制图',
                            root: {
                                expanded: true,
                                children: [
                                    {
                                        id: '',
                                        text: '阈值设置',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: '',
                                        text: '地图显示',
                                        icon: '',
                                        leaf: true
                                    },
                                    {
                                        id: '',
                                        text: '地图管理',
                                        icon: '',
                                        leaf: true
                                    }
                                ]
                            },
                            rootVisible: false,
                            viewConfig: {

                            },
                            listeners: {
                                selectionchange: {
                                    fn: me.onTreepanelSelectionChange3,
                                    scope: me
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    id: 'myTabPanel',
                    layout: {
                        type: 'fit'
                    },
                    title: '',
                    items: [
                        {
                            xtype: 'form',
                            bodyPadding: 10,
                            title: 'UserForm',
                            jsonSubmit: true,
                            url: 'add_user',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    id: 'name',
                                    fieldLabel: 'name',
                                    name: 'name'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    id: 'age',
                                    fieldLabel: 'age',
                                    name: 'age'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        var form = this.up('form').getForm(); // get the basic form
                                        if (form.isValid()) { // make sure the form contains valid data before submitting
                                            form.submit({
                                                success: function(form, action) {
                                                    Ext.Msg.alert('Success', 'chenggong');
                                                },
                                                failure: function(form, action) {
                                                    Ext.Msg.alert('Failed', 'shibai');
                                                }
                                            });
                                        } else { // display error alert if the data is invalid
                                            Ext.Msg.alert('Invalid Data', 'Please correct form errors.');
                                        }

                                    },
                                    text: 'ok'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onTreepanelSelectionChange: function(model, selected, eOpts) {
        var xtype = selected[0].get('id');   
        var tabPanel = Ext.getCmp('myTabPanel');
        tabPanel.removeAll(true);
        tabPanel.add(Ext.widget(xtype));
    },

    onTreepanelSelectionChange1: function(model, selected, eOpts) {
        var xtype = selected[0].get('id');   
        var tabPanel = Ext.getCmp('myTabPanel');
        tabPanel.removeAll(true);
        tabPanel.add(Ext.widget(xtype));
    },

    onTreepanelSelectionChange2: function(model, selected, eOpts) {
        var xtype = selected[0].get('id');   
        var tabPanel = Ext.getCmp('myTabPanel');
        tabPanel.removeAll(true);
        tabPanel.add(Ext.widget(xtype));
    },

    onTreepanelSelectionChange3: function(model, selected, eOpts) {
        var xtype = selected[0].get('id');   
        var tabPanel = Ext.getCmp('myTabPanel');
        tabPanel.removeAll(true);
        tabPanel.add(Ext.widget(xtype));
    }

});