/*
 * File: app/view/QqWeiboDataCatchTab.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.QqWeiboDataCatchTab', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.QqWeiboDataCatchTab',

    id: 'QqWeiboDataCatchTab',
    layout: {
        type: 'fit'
    },
    title: '舆情信息获取',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    id: 'QqNewStatusGrid',
                    title: 'QQ微博列表',
                    forceFit: true,
                    store: 'QqWeiboStore',
                    columns: [
                        {
                            xtype: 'rownumberer',
                            width: 50
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 20,
                            dataIndex: 'id',
                            text: 'id'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 20,
                            dataIndex: 'date',
                            text: 'date'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'text',
                            text: 'text'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'QqWeiboStore'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                Ext.Msg.confirm('您正在发微博数据：', '确认？', getResult);
                                function getResult(confirm)
                                {
                                    console.log('confirm:', confirm);
                                    if (confirm == "yes"){


                                        Ext.Ajax.request({
                                            url:'send_qqweibodata',
                                            params:{testparam:'0'},        
                                            success:function(response){
                                                Ext.Msg.alert('success','发微博成功');                         
                                            },
                                            failure:function(response){
                                                Ext.Msg.alert('failure','发微博失败');      
                                            }

                                        });
                                    }   
                                }
                            },
                            text: '发QQ微博'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                Ext.Msg.confirm('您正在抓取微博数据：', '确认？', getResult);
                                function getResult(confirm)
                                {
                                    console.log('confirm:', confirm);
                                    if (confirm == "yes"){


                                        Ext.Ajax.request({
                                            url:'catch_qqweibodata',
                                            params:{testparam:'0'},        
                                            success:function(response){
                                                var mystore = Ext.StoreMgr.get('QqWeiboStore'); //获得store对象
                                                mystore.load();
                                                Ext.Msg.alert('success','抓取微博成功');                         
                                            },
                                            failure:function(response){
                                                Ext.Msg.alert('failure','抓取微博失败');      
                                            }

                                        });
                                    }   
                                }
                            },
                            text: '抓取QQ微博'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                Ext.Msg.confirm('您正在抓取微博数据：', '确认？', getResult);
                                function getResult(confirm)
                                {
                                    console.log('confirm:', confirm);
                                    if (confirm == "yes"){


                                        Ext.Ajax.request({
                                            url:'parser_json',
                                            //params:{testparam:'0'},        
                                            success:function(response){
                                                var mystore = Ext.StoreMgr.get('QqWeiboStore'); //获得store对象
                                                mystore.load();
                                                Ext.Msg.alert('success','解析微博成功');                         
                                            },
                                            failure:function(response){
                                                Ext.Msg.alert('failure','解析微博失败');      
                                            }

                                        });
                                    }   
                                }
                            },
                            text: '解析json'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                Ext.Msg.confirm('您正在进行分词：', '确认？', getResult);
                                function getResult(confirm)
                                {
                                    console.log('confirm:', confirm);
                                    if (confirm == "yes"){


                                        Ext.Ajax.request({
                                            url:'fenci',
                                            //params:{testparam:'0'},        
                                            success:function(response){
                                                //var mystore = Ext.StoreMgr.get('QqWeiboStore'); //获得store对象
                                                //mystore.load();
                                                Ext.Msg.alert('success','分词成功');                         
                                            },
                                            failure:function(response){
                                                Ext.Msg.alert('failure','分词成功');      
                                            }

                                        });
                                    }   
                                }
                            },
                            text: '中文分词'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});